### PR TITLE
Css for recipe page

### PR DESCRIPTION
**Pull request by Andrew76xx**
Add the CSS for the Individual Recipe page

### CODE REVIEW

**Review by hliu34 — COMMENTED** [review]
Nice, the individual recipe page now looks a lot more organized. LGTM!

**Comment by Baker-C** [comment]
Recipe page looks much better. We still need units for the measurements though.

**Comment by deweklee** [comment]
Looks great andrew! nice work :)

**Review by deweklee — COMMENTED** [review]
nicely done

**Review by tshellenberger — COMMENTED** [review]
Looks great. The new changes for the recipe page work well.

**Pull request merged**
