### PR TITLE
Added Testing for `Modal.jsx`

### PR DESCRIPTION
**Pull request by hliu34**
# Add Tests for Modal Component to Improve Coverage

## Description

This pull request adds comprehensive tests for the `Modal` component to improve test coverage. The `Modal` component now has tests for various prop combinations and user interactions, ensuring all branches and states are covered.

### Changes Made

- Added tests for default props.
- Added tests for custom props with different combinations of `initialName`, `initialQuantity`, `showQuantity`, `isStep`, and `isNew`.
- Verified that the form submission behavior for both new and existing items is correct.
- Checked component's behavior when the cancel button is clicked.
- Improved overall test coverage to 100% for statements, functions, and lines, and 100% for branches.

### Test Coverage

***Before:***

image

***After:***

image

### Checklist

- [x] Added tests to prove that our feature works.
- [x] Verified that all existing tests pass.
- [x] Verified that the code coverage has improved.

## How to Test

1. cd `react-frontend`
2. Run the tests with coverage: `npm test`
3. Verify that the test coverage is accurate 

## Related Issues

- Issue #49 

Please review this PR @Andrew76xx @masterdrek @tshellenberger @Baker-C

### CODE REVIEW

**Review by deweklee — APPROVED** [review]
Looks really good to me! thanks danny :)

**Review by Andrew76xx — COMMENTED** [review]
Good to me too. We got 100% test coverage lets go.

**Review by tshellenberger — COMMENTED** [review]
Testing looks great. Nice job

**Comment by Baker-C** [comment]
It looks great thank you for getting that done Danny

**Pull request merged**
