### PR TITLE
Search based on Inventory (3 hours)

### PR DESCRIPTION
**Pull request by hliu34**
### Description
This pull request implements the feature to filter recipes based on the ingredients available in the user's inventory. The following changes were made:

1. **State Management**:
   - Added state to hold the inventory data.
   - Fetched inventory data when the component is first loaded.

2. **Filtering Logic**:
   - Updated the logic to filter recipes by checking if all ingredients from each recipe exists in the user's inventory.
   - Used the `.every()` method to basically check every element in the ingredient array.

3. **UI Design**:
   - Search filters on change and not upon pressing enter
   - Selecting one of the filters from the dropdown menu will immediately filter based on inventory 

### Changeset
- Modified `Search.jsx`:
  - Added state for inventory.
  - Implemented fetching of inventory data.
  - Updated the useEffect hook to filter recipes based on inventory.

### Please review the following:
1. Ensure that the inventory data is correctly fetched and displayed.
2. Use the search bar and filter dropdown to filter recipes based on available inventory.

### Checklist
- [x] Code compiles correctly?
- [ ] All manual testing passed? (try creating a recipe using similar ingredients in the inventory)

### Related Issues
- Issuse #8 

### Reviewers
@masterdrek  @Andrew76xx @tshellenberger @Baker-C Please review this pull request and provide feedback. Thank You :)

### CODE REVIEW

**Comment by Andrew76xx** [comment]
Search is not working properly as it does not search through the filtered list based on inventory.

**Comment by hliu34** [comment]
> Search is not working properly as it does not search through the filtered list based on inventory.

Noted. It seems the search functionality currently applies to the entire recipe list rather than the filtered list based on inventory. I'll update the code to first filter recipes by inventory and then apply the search query to the filtered list. This should ensure that the search works properly.

**Comment by deweklee** [comment]
Looks good :)

**Review by tshellenberger — COMMENTED** [review]
All of the user interface changes look good and the functionality of the changes seem to match what was described within the pull request.

**Comment by Baker-C** [comment]
Looks good to me. The Search works well.

**Comment by hliu34** [comment]
Ok. merging this branch to main.

**Pull request merged**
